name: iptvzby

on:
  schedule:
    - cron: '0 21 * * *'
  push:
    branches:
      - main
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: GetTime
      run: echo "DATE=$(date +'%Y-%m-%d %H:%M:%S CST')" >> $GITHUB_ENV

    - name: Update
      run: |
       
        # 获取远程文件
        rm -f ipv6.txt && wget https://raw.githubusercontent.com/Meroser/IPTV/main/IPTV-tvbox.txt -O ipv6.txt
        rm -f iptv1.txt && wget https://taoiptv.com/source/iptv.txt?token=8zlxhttq9h01ahww -O iptv1.txt
        #rm -f ipv6.txt && wget https://mirror.ghproxy.com/https://raw.githubusercontent.com/Meroser/IPTV/main/IPTV-tvbox.txt -O ipv6.txt
    - name: Clean
      run: |
        git config --local user.email "mlyuanlang@126.com"
        git config --local user.name "mlvjfchen"
        git checkout --orphan latest_branch
        git add -A
        git commit -am "$DATE"
        git branch -D main
        git branch -m main

    - name: Push
      run: git push -f origin main

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures opencv-python eventlet

      - name: Install Chrome WebDriver
        run: |
          LATEST_CHROMEDRIVER_VERSION=120.0.6099.109
          curl -sS -o chromedriver_linux64.zip "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/linux64/chrome-headless-shell-linux64.zip"
          sudo unzip chromedriver_linux64.zip -d /usr/local/bin
          rm chromedriver_linux64.zip
      - name: Set chromedriver path
        run: |
          sudo ln -sf /usr/local/bin/chrome-headless-shell-linux64/chrome-headless-shell /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run JDY
        run: python ${{ github.workspace }}/iptvzby.py
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: JDY
          path: ${{ github.workspace }}/

      - name: 提交更改
        run: |
          git config --local user.email "mlyuanlang@126.com"
          git config --local user.name "mlvjfchen"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
